nginx:
  image: nginx:alpine
  ports:
    - "80:80"
  depends_on:
    - backend
  volumes:
    - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
    - django-static:/usr/src/app/static
  networks:
    - main
  build:
    context: .
    dockerfile: nginx/dev/Dockerfile
