# Generated by Django 3.0.6 on 2020-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20200520_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='tc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='kimlik numarası'),
        ),
    ]
