# Generated by Django 3.0.6 on 2020-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20200522_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='province',
        ),
        migrations.AddField(
            model_name='appuser',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address 2'),
        ),
    ]
