# Generated by Django 3.0.6 on 2020-05-14 17:21

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün ismi')),
                ('brief', models.CharField(max_length=250, verbose_name='Kısa bilgi')),
                ('description', models.CharField(max_length=1000, verbose_name='Hakkında')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='product_images/', verbose_name='Fotograf')),
            ],
        ),
    ]
